services:
  litellm:
    build:
      context: litellm
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    env_file:
      - .env
    command: --config /app/config.yaml --detailed_debug
    develop:
      watch:
        - action: sync
          path: ./litellm/config.yaml
          target: /app/config.yaml
        - action: rebuild
          path: .env
        - action: rebuild
          path: docker-compose.yaml

  open_webui:
    image: ghcr.io/open-webui/open-webui
    ports:
      - 3000:8080
    env_file:
      - .env
    volumes:
      - ./.open-webui:/app/backend/data
    
  