services:
  litellm:
    build:
      context: litellm
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    env_file:
      - .env
    command: --config /app/config.yaml --detailed_debug
    develop:
      watch:
        - action: sync
          path: ./litellm/config.yaml
          target: /app/config.yaml
        - action: rebuild
          path: .env

  open_webui:
    image: ghcr.io/open-webui/open-webui:dev
    ports:
      - 3000:8080
    env_file:
      - .env
    volumes:
      - ./.open-webui:/app/backend/data

  ai_proxy:
    build:
      context: proxy  
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./proxy/app
          target: /app/app
        - action: rebuild
          path: ./proxy/uv.lock

  
    
  