name: Python Tests
permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit:
    env:
      PROXY_KEY: fake
      AWS_REGION: fake
      AWS_ACCESS_KEY: fake
      AWS_SECRET_ACCESS_KEY: fake
      AZURE_EMBEDDING_ENDPOINT: https://fake.com
      AZURE_EMBEDDING_DEPLOYMENT: fake
      AZURE_EMBEDDING_API_KEY: fake
      AZURE_EMBEDDING_API_VERSION: fake

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./proxy/.python-version"
    - name: Install the project
      run: uv sync --all-extras --dev --directory proxy
    - name: Run tests
      id: run-tests
      run: >
        uv run --directory proxy pytest . \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --log-level=DEBUG \
          --verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./proxy/.python-version"
    - name: Install the project
      run: uv sync --all-extras --dev --directory proxy
    - name: Run mypy
      run: uv run --directory proxy mypy .
