name: Python Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./proxy/.python-version"
    - name: Install the project
      run: cd proxy && uv sync --all-extras --dev
    - name: Run tests
      id: run-tests
      run: >
        uv run pytest . \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --log-level=DEBUG \
          --verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./proxy/.python-version"
    - name: Install the project
      run: cd proxy && uv sync --all-extras --dev
    - name: Run mypy
      run: uv run mypy .